INSERT INTO Players (name) VALUES ('Ivan');
INSERT INTO Players (name) VALUES ('Pavel');
INSERT INTO Players (name) VALUES ('Dmitry');
INSERT INTO Players (name) VALUES ('Sergey');
INSERT INTO Players (name) VALUES ('Valeriy');
INSERT INTO Players (name) VALUES ('Igor');
INSERT INTO Players (name) VALUES ('Petr');
INSERT INTO Players (name) VALUES ('Alexey');
INSERT INTO Players (name) VALUES ('Umar');
INSERT INTO Matches (player1, player2, winner) VALUES (1, 2, 1);
INSERT INTO Matches (player1, player2, winner) VALUES (3, 4, 3);
INSERT INTO Matches (player1, player2, winner) VALUES (5, 6, 6);
INSERT INTO Matches (player1, player2, winner) VALUES (9, 5, 9);
INSERT INTO Matches (player1, player2, winner) VALUES (7, 8, 6);
INSERT INTO Matches (player1, player2, winner) VALUES (3, 6, 5);
INSERT INTO Matches (player1, player2, winner) VALUES (4, 3, 4);
INSERT INTO Matches (player1, player2, winner) VALUES (1, 3, 3);
INSERT INTO Matches (player1, player2, winner) VALUES (2, 5, 2);
INSERT INTO Matches (player1, player2, winner) VALUES (3, 6, 3);
INSERT INTO Matches (player1, player2, winner) VALUES (1, 9, 1);
INSERT INTO Matches (player1, player2, winner) VALUES (1, 4, 1);
INSERT INTO Matches (player1, player2, winner) VALUES (1, 5, 1);
INSERT INTO Matches (player1, player2, winner) VALUES (2, 7, 2);
INSERT INTO Matches (player1, player2, winner) VALUES (3, 8, 8);
INSERT INTO Matches (player1, player2, winner) VALUES (1, 7, 1);
INSERT INTO Matches (player1, player2, winner) VALUES (7, 8, 8);
INSERT INTO Matches (player1, player2, winner) VALUES (9, 2, 2);
INSERT INTO Matches (player1, player2, winner) VALUES (2, 4, 2);
INSERT INTO Matches (player1, player2, winner) VALUES (4, 7, 4);
INSERT INTO Matches (player1, player2, winner) VALUES (4, 6, 6);
INSERT INTO Matches (player1, player2, winner) VALUES (3, 5, 5);
INSERT INTO Matches (player1, player2, winner) VALUES (1, 8, 8);
INSERT INTO Matches (player1, player2, winner) VALUES (4, 9, 9);
INSERT INTO Matches (player1, player2, winner) VALUES (7, 5, 5);
INSERT INTO Matches (player1, player2, winner) VALUES (2, 1, 2);
INSERT INTO Matches (player1, player2, winner) VALUES (1, 5, 5);
INSERT INTO Matches (player1, player2, winner) VALUES (1, 6, 6);
INSERT INTO Matches (player1, player2, winner) VALUES (8, 9, 8);